export const FETCH_SONGS_REQUEST = 'FETCH_SONGS_REQUEST';
export type FETCH_SONGS_REQUEST = typeof FETCH_SONGS_REQUEST;

export const FETCH_SONGS_SUCCESS = 'FETCH_SONGS_SUCCESS';
export type FETCH_SONGS_SUCCESS = typeof FETCH_SONGS_SUCCESS;